#!/usr/bin/env bash
set -e # Abort on errors

if [[ -z $BACKTOSKOOL_HOME ]]; then
  echo "Error: BACKTOSKOOL_HOME not defined."
  exit 1
fi
if [[ ! -d $BACKTOSKOOL_HOME ]]; then
  echo "Error: directory not found: $BACKTOSKOOL_HOME"
  exit 1
fi

if [[ -z $SKOOLKIT_HOME ]]; then
  echo "Error: SKOOLKIT_HOME not defined."
  exit 1
fi
if [[ ! -d $SKOOLKIT_HOME ]]; then
  echo "Error: directory not found: $SKOOLKIT_HOME"
  exit 1
fi

DHOME=$BACKTOSKOOL_HOME

. $DHOME/.dreleaserc

. $SKOOLKIT_HOME/tools/drelease-functions

parse_args $*
